### ISSUE TITLE
Support for Understanding VPC-related Network Information

### ISSUE THREAD

**Issue by gmolto** [indigo-dc/im#132]
Certain instance types and AMIs in AWS have to be deployed on a subnet of a VPC. There should be a way to specify the subnet on which an infrastructure described in TOSCA has to be deployed by the IM:

Maybe we can use the following syntax:

sample_server:
      type: tosca.nodes.indigo.Compute
      capabilities:
        endpoint:
          properties:
            network_name: **vpc-6366c106.subnet-de5252f6.public** 
            ports:
              http_port:
                protocol: tcp
                source: 80

This identifies the VPC, the subnet and a tag that indicates that the VM will be deployed on a public subnet.

**Comment by micafer** [comment]
The final public must be uppercase:
network_name: vpc-6366c106.subnet-de5252f6.**PUBLIC**

**Comment by gmolto** [comment]
Great. This solves this issue and allows deployment of TOSCA-based infrastructures in subnets of VPCs in AWS. 

Good work!
