### ISSUE TITLE
DependencyViolation when deploying the Mesos TOSCA Template

### ISSUE THREAD

**Issue by gmolto** [indigo-dc/im#134]
I submitted the attached TOSCA template to the IM to be deployed on AWS but I obtained the following error:

Error Creating Inf.: Some deploys did not proceed successfully: All machines could not be launched: 
Attempt 1: Error launching the VMs of type mesos_master_server to cloud ID aws of type EC2. Cloud Provider Error: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>DependencyViolation</Code><Message>resource sg-f212a08e has a dependent object</Message></Error></Errors><RequestID>2a3f2ba6-0499-4f75-ba82-d1cfa5815f3f</RequestID></Response>

Any hints?

[mesos-aws.txt](https://github.com/indigo-dc/im/files/735089/mesos-aws.txt)

**Comment by micafer** [comment]
Solved in the upstream.

**Comment by micafer** [comment]
Merged
