### ISSUE TITLE
IM not finding Image at URL

### ISSUE THREAD

**Issue by norealroots** [indigo-dc/im#178]
I am currently working on deploying an IM instance as a test case to work alongside our Openstack cloud, however I am having issues with defining the image URL in the RADL and getting it to succesfully deploying a VM. I have modified the image_url.radl file found [here ](https://github.com/grycap/im/blob/master/examples/image_url.radl) with the URL for the image I would like to use, however this results in this error:

> ERROR creating the infrastructure: Some deploys did not proceed successfully: All machines could not be launched:
> Attempt 1: Error, no concrete system to deploy: test in cloud: openstack. Check if a correct image is being used
> 

I have looked through the InfrastructureManager.py file to try and place where this issue is occuring, but to no avail thus far. I was hoping for some pointers on where I may be going wrong with this. I will be at the summit next week and so would appreciate the opportunity to perhaps discuss this there also.

Many thanks!

**Comment by micafer** [comment]
Hi @norealroots,

You can see the RADL documentation at: http://imdocs.readthedocs.io/en/latest/radl.html
There you can see the format of the url.

The RADL for the OpenStack simple tests must be something like this:

network publica (outbound = 'yes')
```yaml
system test (
cpu.arch='x86_64' and
cpu.count>=1 and
memory.size>=512M and
net_interface.0.connection = 'publica' and
disk.0.image.url = 'ost://<keystone_host_name>/<image_id>' and
disk.0.os.name = 'linux'
)

deploy test 1
```

Remember that you also need to pass the correct auth credentials to the im-client or IM web portal to access the site see: http://imdocs.readthedocs.io/en/latest/client.html#auth-file. The simple case is like this:

```
id = ost; type = OpenStack; host = https://<keystone_host_name>:5000; username = user; password = pass; tenant = tenant
```

But there are other additional fields that may be necessary depending on the OpenStack site configuration, see: http://imdocs.readthedocs.io/en/latest/client.html#openstack-additional-fields

**Comment by norealroots** [comment]
Hi @micafer

I updated the RADL and Auth file based on your response, with details for our config from the admin. Despite this I am still recieving the same error - there is no concrete system to deploy. Do you have any other ideas of what may be causing this?

Many thanks.

**Comment by micafer** [comment]
Hi,

This error appears when the url of the image specified in the RADL does not match with the data specified in the auth data.

Are you using the im-client tool?

Can you show the exact RADL and the auth data line?

**Comment by norealroots** [comment]
Hi,

I'm using the client, yes (though I did have an issue with using the im_client.cfg file rather than calling the host and auth file in the im_client command).

The RADL is:

`network public (outbound = 'yes')

system test (
cpu.arch='x86_64' and
cpu.count>=1 and
memory.size>=512M and
net_interface.0.connection = 'public' and
disk.0.image.url = 'ost://~hostname~:5000/v2/image/b9a00e23-a5fb-434a-b471-651d21eefd09' and
disk.0.os.name = 'linux'
)

deploy test 1`

and the auth-line is:

`id = ost; type = OpenStack; host = https://~hostname~:5000; username = ~user~; password = ~password~; tenant = Indigo Infrastructure Manager; auth_version = 3.X_password`

Thanks

**Comment by micafer** [comment]
Hi,

The url image is incorrect, it should be:
```
'ost://hostname/b9a00e23-a5fb-434a-b471-651d21eefd09'
```

Could you try with this one?

**Comment by norealroots** [comment]
Just updared the url to:

`disk.0.image.url = 'ost://hostname:5000/b9a00e23-a5fb-434a-b471-651d21eefd09' `

and got 

```
im_client.py -u http://localhost:8899 -a ~/IM/.IMAuthFile.dat create simpleImage.radl
Connected with: http://localhost:8899
ERROR creating the infrastructure: Some deploys did not proceed successfully: All machines could not be launched:
Attempt 1: Error, no concrete system to deploy: test in cloud: ost. Check if a correct image is being used
```
again. 

Any thoughts?

**Comment by micafer** [comment]
We manage to make it work at the INDIGO summit.
