### ISSUE TITLE
Suggestion for Documentation Update

### ISSUE THREAD

**Issue by norealroots** [indigo-dc/im#203]
If possible, a direct link to the IM client in the documentation for IM would be useful, and would make the documentation more comprehensive. 

Thanks

**Comment by micafer** [comment]
Hi @norealroots,

In the case of INDIGO, where TOSCA is used, a link to the im-client has not been included as currently it does not support it. IM client currently only supports RADL.
Using TOSCA as input a REST client must be used (curl, [Postman](https://www.getpostman.com/), [Restlet Client](https://chrome.google.com/webstore/detail/restlet-client-rest-api-t/aejoelaoggembcahagimdiliamlcdmfm), ...).

Best regards.
