### ISSUE TITLE
Problems with the SLURM RADL example

### ISSUE THREAD

**Issue by alahiff** [indigo-dc/im#220]
I tried to use the slurm RADL example (i.e. https://github.com/indigo-dc/im/blob/master/examples/slurm.radl) to deploy a SLURM cluster on EGI FedCloud but encountered some problems.

Since I currently just have a test IM instance (using the latest Docker image) and no VMRC I added a line to the system front and wn sections of the RADL file specifying the EGI Ubuntu image:
```
disk.0.image.url='https://carach5.ics.muni.cz:11443/uuid_38d42ca1_f4e9_5b5c_98de_37eb2d26301a_warg_default_shared_218' and
```
In this case the VMs enter the running state but then become "unconfigured". I see an error:
```
TASK [Ubuntu install Ansible requisites with apt] ******************************
fatal: [147.228.242.23]: FAILED! => {"changed": false, "msg": "Failed to lock apt for exclusive operation"}
```
If I switch to using the EGI CentOS 7 image by adding the following line in the appropriate places:
```
disk.0.image.url='https://carach5.ics.muni.cz:11443/uuid_fe71524e_66d3_5d09_8375_c5510ed5ccba_warg_default_shared_230' and
```
the front-end node is successfully configured but the two worker nodes end up unconfigured. In this case I see the error:
```
TASK [indigo-dc.nfs : Wait NFS server to be up] ********************************
fatal: [147.228.242.31_2]: FAILED! => {"failed": true, "msg": "[{u'remote': u'/home', u'local': u'/home', u'server_host': u'{{ slurm_front_end_ip }}'}]: {{ hostvars[ groups['front'][0]]['IM_NODE_NET_0_IP'] }}: 'dict object' has no attribute 'IM_NODE_NET_0_IP'"}
```
Note that if I replace IM_NODE_NET_0_IP in slurm.radl with IM_NODE_PRIVATE_IP then the two worker nodes can be successfully configured and I end up with a functioning SLURM cluster.

Finally, maybe this is outside of the scope of the simple SLURM example, but it seems that the `/etc/slurm/slurm.conf` files are different on each of the hosts. On the front-end there is this at the end of the file:
```
# COMPUTE NODES 
NodeName=vnode-1,vnode-2 CPUs=1 State=UNKNOWN
PartitionName=debug Nodes=vnode-1,vnode-2 Default=YES MaxTime=INFINITE State=UP
```
on one worker node:
```
# COMPUTE NODES 
NodeName=vnode-1 CPUs=1 State=UNKNOWN 
PartitionName=debug Nodes=vnode-1 Default=YES MaxTime=INFINITE State=UP
```
and on the other:
```
# COMPUTE NODES 
NodeName=vnode-2 CPUs=1 State=UNKNOWN 
PartitionName=debug Nodes=vnode-2 Default=YES MaxTime=INFINITE State=UP
```
I think SLURM prefers to have identical configuration files on all hosts. One problem caused by the different config files are errors when trying to run MPI jobs. If I modify slurm.radl to install OpenMPI on the worker nodes and run a test MPI job I get this error:
```
srun: error: fwd_tree_thread: can't find address for host vnode-2, check slurm.conf
srun: error: Task launch for 6.0 failed on node vnode-2: Can't find an address, check slurm.conf
srun: error: Application launch failed: Can't find an address, check slurm.conf
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
mpirun (Open MPI) 1.10.6
```
I found a simple workaround for this is to change this in the "configure wn" part of the slurm.radl:
```
  - role: indigo-dc.slurm
    slurm_type_of_node: 'wn'
    slurm_server_ip: "{{ slurm_front_end_ip }}"
```
to this:
```
  - role: indigo-dc.slurm
    slurm_type_of_node: 'wn'
    slurm_server_ip: "{{ slurm_front_end_ip }}"
    slurm_wn_ips: '{{ groups["wn"]|map("extract", hostvars, "ansible_default_ipv4.address")|list if "wn" in groups else [] }}'
    slurm_wn_nodenames: '{{ groups["wn"]|map("extract", hostvars, "ansible_hostname")|list if "wn" in groups else [] }}'
```
i.e. using the same slurm_wn_ips and slurm_wn_nodenames as is used for the front-end node. With this change identical SLURM configuration files are generated on each VM which makes it possible for MPI jobs to work.

**Comment by micafer** [comment]
All this errors are not directly related with the IM but let me answer:

* The error: 
> Failed to lock apt for exclusive operation
Is a problem of some ubuntu images that has an automated apt upgrade on boot process. It makes other apt process to fail.

* The error:
> fatal: [147.228.242.31_2]: FAILED! => {"failed": true, "msg": "[{u'remote': u'/home', u'local': u'/home', u'server_host': u'{{ slurm_front_end_ip }}'}]: {{ hostvars[ groups['front'][0]]['IM_NODE_NET_0_IP'] }}: 'dict object' has no attribute 'IM_NODE_NET_0_IP'"}
You are right it must be changed to IM_NODE_PRIVATE_IP. I will update the example.

* Finally the /etc/slurm/slurm.conf file: I will try your proposal and update the example.
