### ISSUE TITLE
cloudinit runcmd is overwritten

### ISSUE THREAD

**Issue by maricaantonacci** [indigo-dc/im#249]
Hi,

it seems that, starting from version 1.7.5, the IM overwrites the runcmd command.
At our cloud site we have configured cloudinit in the images in order to execute a script at boot that ensures the proper functioning of the virtual machines. 
As a matter of fact, the deployments launched through IM v1.7.5 are failing at our site.

More in general, the boot operations configured in cloudinit by the cloud site admins should be preserved since, as in our case, they might be related to specific features of the site that only the admin knows. What do you think?

**Comment by micafer** [comment]
Hi @maricaantonacci,

This is due to the commands set by the IM to activate the ssh reverse tunnels.
We will check how to avoid that the IM commands overwrite the site ones.

In the meanwhile you can deactivate it setting this variable in the im.cfg file:
```
SSH_REVERSE_TUNNELS = False
```

**Comment by micafer** [comment]
The solution proposed  in: https://github.com/grycap/im/issues/695 of using #cloud-config-jsonp instead of #cloud-config does not fix the problem.
In your case the runcmd is specified at the cloud.cfg file and in this case the "merge" functions does not work as expected. It is a cloud-init issue:
https://bugs.launchpad.net/cloud-init/+bug/1532234

**Comment by micafer** [comment]
Hi @maricaantonacci,
Did you tried to add the runcmd command in the vendor-data files instead of in the cloud.cfg?
https://cloudinit.readthedocs.io/en/latest/topics/datasources/openstack.html#vendor-data

**Comment by maricaantonacci** [comment]
Hi @micafer,

not yet. Do you have a working example for the vendor-data file?

**Comment by micafer** [comment]
Hi @maricaantonacci,
I'm not an expert on cloud-init.
But using your current alternative any user that uses user-data setting a runcmd will overwrite your current command. May be you can execute your script using another alternative.

**Comment by maricaantonacci** [comment]
Hi @micafer 
we are investigating other solutions for running our script.
